# Generated by Django 4.1.3 on 2022-11-11 16:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arie",
            fields=[
                ("gid", models.BigIntegerField()),
                (
                    "id",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("categoria", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=133)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "verbose_name_plural": "Arii Protejate",
            },
        ),
        migrations.CreateModel(
            name="AriePoint",
            fields=[
                ("objectid", models.BigIntegerField()),
                ("id", models.FloatField(primary_key=True, serialize=False)),
                ("denumirea", models.CharField(max_length=254)),
                ("suprafata", models.FloatField()),
                ("infiintari", models.FloatField()),
                ("categorie", models.FloatField()),
                ("mn_id", models.FloatField()),
                ("pa_code", models.FloatField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
                ),
            ],
            options={
                "verbose_name_plural": "Arii Protejate (puncte)",
            },
        ),
        migrations.CreateModel(
            name="Localitate",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("osm_id", models.CharField(max_length=10)),
                ("code", models.BigIntegerField()),
                ("fclass", models.CharField(max_length=28)),
                ("population", models.FloatField()),
                ("name", models.CharField(max_length=100)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
                ),
            ],
            options={
                "verbose_name_plural": "Localități",
            },
        ),
        migrations.CreateModel(
            name="Locatie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                "verbose_name_plural": "Locații",
            },
        ),
        migrations.CreateModel(
            name="Rn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                ("type", models.CharField(max_length=50)),
                ("engtype", models.CharField(max_length=50)),
                ("gid", models.CharField(max_length=10)),
                ("hasc", models.CharField(max_length=10)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "verbose_name_plural": "Raioane",
            },
        ),
        migrations.CreateModel(
            name="Tara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                ("cuatm", models.CharField(max_length=254)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "verbose_name_plural": "Țări",
            },
        ),
    ]
