# Generated by Django 4.1.3 on 2022-11-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Arie",
            new_name="Area",
        ),
        migrations.RenameModel(
            old_name="AriePoint",
            new_name="AreaPoint",
        ),
        migrations.RenameModel(
            old_name="Tara",
            new_name="Country",
        ),
        migrations.RenameModel(
            old_name="Rn",
            new_name="District",
        ),
        migrations.RenameModel(
            old_name="Localitate",
            new_name="Locality",
        ),
        migrations.RenameModel(
            old_name="Locatie",
            new_name="Location",
        ),
        migrations.AlterModelOptions(
            name="area",
            options={"verbose_name_plural": "Protected Areas"},
        ),
        migrations.AlterModelOptions(
            name="areapoint",
            options={"verbose_name_plural": "Protected Areas (points)"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="district",
            options={"verbose_name_plural": "Districts"},
        ),
        migrations.AlterModelOptions(
            name="locality",
            options={"verbose_name_plural": "Localities"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name_plural": "Locations"},
        ),
    ]
